### PR TITLE
add e.stopPropagation(); to drop handler

### PR DESCRIPTION
**Pull request by rqx110**
in FireFox, when drop a file, it will open a new tab.
add e.stopPropagation(); to fix this problem.

### CODE REVIEW

**Comment by jsakamoto** [comment]
@rqx110 Thank you for your contribution!

By the way, I was not able to reproduce the problem that you reported in my environment.

- OS: Windows 11 x64
- Browser: Firefox ver.100.0
- App: https://jsakamoto.github.io/Toolbelt.Blazor.FileDropZone/

When I drag & drop image files (.jpg and .png) onto the drop zone in the above Blazor WebAssembly app, it works expectedly, and it doesn't open those image files in a new tab.

Could you tell me more details about your environment and what you experienced?

**Comment by rqx110** [comment]
see the GIF image:
ff

**Comment by rqx110** [comment]
I found it may relate my localize(zh-CN) Firefox version. while I install the other version(e.g. English) it works. It is very strange!!
But still hope to accept this PR which can fix special firefox version problem .

**Comment by jsakamoto** [comment]
@rqx110 Thank you for your detailed report!

> But still hope to accept this PR which can fix special firefox version problem .

OK, I understood.
It might be a breaking change, but anyway, I'll accept this PR.

And in the future release, I'll add the `EnablePropergation` options to save the users who really want to catch the drop event outside of the `FileDropZone` component.

**Comment by jsakamoto** [comment]
@rqx110 

I released ver.2.0.0.
- https://www.nuget.org/packages/Toolbelt.Blazor.FileDropZone/2.0.0

Please try it out.

And again, thank you for your contribution! 👍

**Pull request merged**
